### ISSUE TITLE
Cannot leave dungeon room

### ISSUE THREAD

**Issue by plaidpants** [ergonomy-joe/u4-decompiled#11]
Ran into issues in the dungeon where the second person in the party to leave as dungeon room could not leave. Traced the issue down to some signed vs. unsigned code.

These two variables record the first exit of a party character from a dungeon room so we can make sure everyone leaves the same way, notice that they are signed chars.
```
char D_96EE;
char D_96F4;
```

the code make liberal use unsigned values to avoid needing to check for negatives and positive values by casting to unsigned and then only check for >10 which will catch both the case of 11 and the case of -1 when the character leaves.
```
in C_7AE3(si/*bp08*/, bp06, bp04)
register int si;
unsigned char bp06;
unsigned char bp04;

	/*-- out of bounds=>exiting*/
	if((unsigned)bp06 > 10 || (unsigned)bp04 > 10) {
		C_79C9(bp06, bp04);
		return;
	}

```

However the exiting dungeon code will assign the unsigned bp06 to the signed D_96EE or the unsigned bp04 to the signed D_96F4 which will cause issues as the compiler will strip off the upper bits or other undefined behavior before assigning to the signed variable during the assignment operator. Need to cast the value prior to the assignment and cast the value before the if() checks if we want it to work like the original code so we can be explicit as to how we want the compiler to treat these values.

```
/*exiting fight*/
C_79C9(bp06, bp04)
unsigned char bp06;
unsigned char bp04;
{
	if(CurMode == MOD_COM_ROOM) {
		/*-- dungeon room --*/
		if(D_96EE != 0) {
			if(bp06 == D_96EE)
				goto C_7A0C;
			w_SameExit();
			return;
		} else if(D_96F4 != 0) {
			if(bp04 == D_96F4)
				goto C_7A0C;
			w_SameExit();
			return;
		} else if(bp06 > 10) {
			D_96EE = bp06;
		} else {
			D_96F4 = bp04;
		}
	}
C_7A0C:
	C_7962();
}
```

Maybe the function should be something like this instead where the unsigned and signed values are more explicit to match what the code is originally doing.

```
/*exiting fight*/
C_79C9(bp06, bp04)
unsigned char bp06;
unsigned char bp04;
{
	if(CurMode == MOD_COM_ROOM) {
		/*-- dungeon room --*/
		if(D_96EE != 0) {
			if(bp06 == (unsigned char)D_96EE)
				goto C_7A0C;
			w_SameExit();
			return;
		} else if(D_96F4 != 0) {
			if(bp04 == (unsigned char)D_96F4)
				goto C_7A0C;
			w_SameExit();
			return;
		} else if(bp06 > 10) {
			D_96EE = (char)bp06;
		} else {
			D_96F4 =  (char)bp04;
		}
	}
C_7A0C:
	C_7962();
}
```

FYI, Here is some dungeon action.

https://youtu.be/EPxrigiMmR8

**Comment by ergonomy-joe** [comment]
@plaidpants I could reproduce the problem, and then I tried building with your fix.
Since it works for me too, and doesn't change the generated msdos's EXE I commited it. Thanks !

nice video btw
