### ISSUE TITLE
Modify and compile for mods?

### ISSUE THREAD

**Issue by cambragol** [ergonomy-joe/u4-decompiled#2]
Hi, I just stumbled across this project and was amazed at what you have accomplished. I have been building modifications to the original Ultima IV via hex editing and through the use of a variety of tools I have gathered around the web. I am not really a coder, but have modded other games extensively. 

However, I can now see that hex editing my changes into the original exe will not really work, and at best can only replace existing content. However, if your reverse engineered code could be recompiled, with a few changes to accommodate new dungeons, towns, maps, .tlk files etc, then my modifications could have a home.

So my question is, before I dive into figuring out how to compile your code correctly, can this code be recompiled to a working exe? And if yes, could you perhaps pass on some hints/instructions to make the task a little lighter?

Any help or feedback would be appreciated.

Cheers.

**Comment by cambragol** [comment]
Well, I got the build environment all figured out. It compiles nicely and the exe is just a few bytes bigger. Amazing work.

**Comment by ergonomy-joe** [comment]
Hi There,

I'm a little late on the answer so it seems that you already managed to rebuild the EXE. Congratulations.
Let me know when your project is finished.

The original project used the Microsoft C compiler version 4.0. Which I believe is the one used by the original programmer too.

As a personnal project I could build this code to a Windows 32 bit exe (using Visual Studio).
Of course I had to rewrite all the ASM functions, add a Winmain, change some stuff in the code but ... it worked !! When I have time I'll try to post the project.

**Comment by cambragol** [comment]
Thanks for getting back to me. I really truly appreciate the work you did reverse engineering the code. It has allowed me to modify my all time favorite game to my heart's content. A true joy. Many thanks to you.

I have a project that I am working on for my personal enjoyment which will add a lot of new content to the original game, as well as a new side plot. So far I have second floors for all towns, and 8 new villages, and 3 new dungeons. I fixed some bugs that were in the original game, regarding traps on chests, as well as saving moon positions among a few other things. I have repository on Github, but I am currently keeping track of the project using svn locally. I am not so familiar with git, but I'll update things here for other peoples sake. Someone might be interested in it when it is done.

I managed to track down Microsoft C compiler 4.0 and its documentation and built the exe with that. I currently have a nice little build/test environment inside of 'Boxer' which is the osx version of Dosbox.

I would definitely be interested in seeing your Windows 32 version. I think I even spotted a chunk of code here and there from that in the decompiled code. I thought about taking a stab at compiling it for Osx, but that would be beyond me currently.

Here is a link to the repository I have set up for the project. Again, I am not familiar with git, and am kindof just fooling about with the repository at the moment. But there it is.

https://github.com/cambragol/ultima-IV-trinity

Cheers!

**Comment by cambragol** [comment]
Hi again,

I apologize for reopening this 'issue' but it seems the logical point to continue the thread of discussion. I have hit a fairly serious impasse with the code, namely, running out of memory. 64K is the max for these old DOS programs, as you are likely aware. I have tried my level best to recompile the mod in different ways, but it seems rewriting the assembly code might be the only solution. However, your mention of a working windows 32 build gives me hope. I have run right into the wall of this 64k code limit, and have had to keep cutting back on features and code that I was hoping to include in the final version of the mod. A windows 32 version would, I assume, eliminate this 64k limit, and allow me to include features.
Any possibility of uploading what you have working? Or even making an OSX or rewritten 'Large' program for DOS?
Just wondering. In the meantime I am finishing up things with my mod, and have squeezed in as much as I can into the 64k limit.

**Comment by ergonomy-joe** [comment]
I uploaded a new folder: forVS
If you have Visual Studio 97 or Visual Studio 2008 you can use the project files inside.
If you have another version it may not be too hard to do the conversion.
Hope you can build it and give me some feedback !
Bye
