### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by rdanbrook** [ergonomy-joe/u4-decompiled#4]
I am curious about what kinds of intellectual property restrictions may exist on this code. I am working on a fork of xu4 right now and I want to reference this code perhaps, but I'm not sure if that would taint me in some way. I don't really know much about the legalities of working with decompiled code. If you could offer any insight into that, it would be great. If not, then no worries.

**Comment by ergonomy-joe** [comment]
Hi rdanbrook. Sorry for the delay.
I cannot say much about the copyright. I think the decompiled code belongs to the current copyright owner of the game itself.
Concerning my work, feel free to use it as is it. With maybe a little nod, if you find it useful.
But I cannot garantee there won't be any legal action from the actual property owner ...
