### ISSUE TITLE
Guards run away

### ISSUE THREAD

**Issue by plaidpants** [ergonomy-joe/u4-decompiled#9]
I compiled and built this using VS2019, I noticed that if I attack the guards they will run away which doesn't seem like correct behavior.

**Comment by cambragol** [comment]
That is weird. That behavior would happen if their hitpoints are below a certain level. So maybe your build is reading their hitpoints wrong somehow. Hitpoints are stored in a variable which is an 'unsigned char'. Perhaps VS2019 deals with 'unsigned Char' types differently?

**Comment by plaidpants** [comment]
hit points get set here

```
/*init fighters info?*/
C_7E7E()
```

guard tile is 0x50
fighter tile gets set here, loc_D is the fighter index loc_E is the tile

`Fighters._tile[loc_D] = Fighters._gtile[loc_D] = loc_E;`

```
loc_C = D_23D2[C_7C25(loc_E)];

C_7C25(bp04)
unsigned char bp04;
{
	if(bp04 >= TIL_80) {
		bp04 &= 0x7f;
		if((bp04 >> 1) < 8)
			return bp04 >> 1;
		return (bp04 >> 2) + 4;
	}
	return (bp04&0x1f) + 0x24;
}
```

bp04 is less than 0x80 (i.e. guard tile is 0x50) so C_7C25() returns (0x50&0x1f) + 0x24 = 0x34

```
/*enemy HP*/
unsigned char D_23D2[] = {
 0xFF,0xFF,0x40,0x60,0x80,0x60,0xFF,0xFF,0x30,0x30,0x40,0x50,0x30,0x60,0x30,0xC0,
 0xFF,0x30,0xF0,0x80,0x50,0x30,0x50,0x30,0x70,0x40,0x80,0x40,0xB0,0xC0,0x60,0xF0,
 0x70,0xD0,0xE0,0xFF,0x70,0x30,0x60,0x40,0x60,0x80,0x90,0x30,0x80,0x30,0x30,0x30,
 0x20,0x20,0x80,0xFF
};
```

however D_23D2[] is only 0x34 bytes in size so we return unknown data just after the last byte?

// in my VS2019 case this results in the guards HP being assigned 0 which causes them to flee

`Fighters._HP[loc_D] = (loc_C >> 1) | U4_RND4(loc_C);`

Also in another location for setting HP in the dungeon you mention a possible bug

```
		if(loc_A._010/*bug?*/) {
		/*shouldn't be "if(loc_A._010[loc_B]) {" ?*/
```

<img width="1280" alt="screenshotHP" src="https://user-images.githubusercontent.com/8979271/157707555-b589922b-1383-47e9-94dc-f4ac60263302.png">

**Comment by plaidpants** [comment]
Filling the array up with something results in better guard behavior. The question is what is the actual data in question

```
/*enemy HP*/
unsigned char D_23D2[] = {
	0xFF,0xFF,0x40,0x60,0x80,0x60,0xFF,0xFF,0x30,0x30,0x40,0x50,0x30,
	0x60,0x30,0xC0,0xFF,0x30,0xF0,0x80,0x50,0x30,0x50,0x30,0x70,0x40,
	0x80,0x40,0xB0,0xC0,0x60,0xF0,0x70,0xD0,0xE0,0xFF,0x70,0x30,0x60,
	0x40,0x60,0x80,0x90,0x30,0x80,0x30,0x30,0x30,0x20,0x20,0x80,0xFF,
	0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
	0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
};
```

I find this data in the AVATAR.EXE

```
ff ff 40 60 80 60 ff ff 30 30 40 50 30 60 30 c0
ff 30 f0 80 50 30 50 30 70 40 80 40 b0 c0 60 f0
70 d0 e0 ff 70 30 60 40 60 80 90 30 80 30 30 30
20 20 80 ff c8 c8 8a 88 86 84 8c 8e c4 e9 90 e4
a0 d0 a8 ac b0 90 bc 9c a4 e0 c8 90 f0 b8 ec bc
f0 f0 f4 b8 fc f8 fc fc 01 01 0c 04 04 08 01 01
0c 0c 06 04 0f 06 0f 01 01 0f 04 08 0a 0c 0a 0c
06 08 06 0c 06 04 08 04 06 04 04 01 00 00 08 10
18 20 28 30 40 28 38 40 60 60
```
![image](https://user-images.githubusercontent.com/8979271/157709537-dd3c76b4-0991-4e6f-a800-61f23b34ce78.png)

**Comment by plaidpants** [comment]
I think this statement should be `return (bp04&**0x0f**) + 0x24;` as the last tile is 252 for the monsters and results in 0x23 in `return (bp04 >> 2) + 4;` and 0xff for the guard which would make sense when looking at the table.

**Comment by Fenyx4** [comment]
Holy off by one error batman!

I modified the code to output some values to see what was actually happening.

TILE: 0x50
C_7C25[0x50] result: 0x34
D_23D2[C_7C25[0x50]] result: 0xc8

Which as you pointed out above is the first value off the end of the array.

Compiling in VS2019 must be sticking other random values after the array.

**Comment by Fenyx4** [comment]
Also those Unity screenshots look VERY interesting.

**Comment by plaidpants** [comment]
:-)

**Comment by Fenyx4** [comment]
> I think this statement should be `return (bp04&**0x0f**) + 0x24;` as the last tile is 252 for the monsters and results in 0x23 in `return (bp04 >> 2) + 4;` and 0xff for the guard which would make sense when looking at the table.

This does fix it by not overrunning the array but it does change a lot of NPCs hitpoints. None of the ones that changed look particularly bad to me. Guards are less tough though. I'm curious if the apple ii version had the same bug...

Name | Before | After
-- | -- | --
Guard | 200 | 112
Jester | 140 | 144
Bard Lute player | 134 | 96
Merchant | 138 | 96
LB | 168 | 128
Beggar | 196 | 128
Mage | 176 | 176
Shepherd | 128 | 128
Body | 196 | 128
Ranger | 32 | 32
Child | 144 | 48

**Comment by plaidpants** [comment]
foe_index_from_tile:
	bpl @not_monster
	and #$7f
	lsr
	cmp #$08     ;%1000NNNx
	bcc @done
	lsr          ;%1NNNNNxx + 4
	clc
	adc #$04
@done:
	rts
@not_monster:
	and #$1e     ;%000NNNNx + 24  (BUGFIX: was 1f, %000NNNNN)
	lsr          ;BUGFIX: was clc
	adc #$24
	rts

from [https://github.com/sean-gugler/u4remasteredA2/releases](here)
so the apple2 version was 1f but it was changed to 1e and then bit shifted, this is the equivalent.

return ((bp04&0x1e) >> 1) + 0x24

this is what xu4 has in its data
```
    <creature id="10" name="Guard" tile="guard" basehp="128" exp="13" good="true" wontattack="true"/>
    <creature id="11" name="Merchant" tile="villager" basehp="48" exp="9" good="true" wontattack="true"/>
    <creature id="12" name="Bard" tile="bard_singing" basehp="48" exp="9" good="true" wontattack="true"/>
    <creature id="13" name="Jester" tile="jester" basehp="48" exp="9" good="true" wontattack="true"/>
    <creature id="14" name="Beggar" tile="beggar" basehp="32" exp="13" good="true" wontattack="true"/>
    <creature id="15" name="Child" tile="child" basehp="32" exp="10" good="true" wontattack="true"/>
    <creature id="16" name="Bull" tile="bull" basehp="128" exp="11" good="true"/>
    <creature id="17" name="Lord British" tile="lord_british" basehp="255" exp="16" ranged="true" rangedhittile="magic_flash" rangedmisstile="magic_flash" good="true" wontattack="true"/>
```

**Comment by Fenyx4** [comment]
| 1f | 0f | 0e >> 1
-- | -- | -- | --
Guard | 200 | 112 | 128
Jester | 140 | 144 | 48
Bard Lute player | 134 | 96 | 48
Merchant | 138 | 96 | 48
LB | 168 | 128 | 255
Beggar | 196 | 128 | 32
Mage | 176 | 176 | 176
Shepherd | 128 | 128 | 48
Body | 196 | 128 | 32
Ranger | 32 | 32 | 144
Child | 144 | 48 | 32


Ran through Castle British again. These values all make a lot of sense... Maxed out LB. Tough guards (Although not as tough as original.) Rest of the citizens weaker except for the Ranger who is tougher which makes sense.

**Comment by Fenyx4** [comment]
Good to know it was buggy in Apple II too. 

I really need to learn assembly one of these days.

Interesting that xu4 appears to have the same 1e >> 1 values as the u4 remaster.

**Comment by cambragol** [comment]
Hmph. This relates to a lot of issues I had previously, when switching from 4 to 3 frame sprites in my code. And adding new monsters.

**Comment by ergonomy-joe** [comment]
That is a really interesting issue.
Thank you @plaidpants for raising it and @Fenyx4 for your research.
Watching the data, it seems obivous that the correct code should be `((bp04&0x1f) >> 1) + 0x24` (or 0x1e, it doesn't matter).

Since it is an issue from the original binary, I think this is how I will modify `U4_COMBC.C`:
.putting the correct code inside an `#ifdef WIN32`.
.reformat the arrays to make them more readable
.add some comments

Don't know when it will be done though  ^^;

ps: thanks to this thread, I also managed to understand what the array `D_2406` is for; I will label it [enemy tile "partners"]
